feat: output the entire scan result to the github summary
nrkno/github-workflow-docker-build-push pull request #31
Opened 2023-06-13 14:29 UTC by siljekristensen

I would like to have the Trivy scan result available in the summary, but this is not a very elegant solution. Input wanted!

2023-06-13 15:10 UTC, stigok requested changes
Tror på sikt det vil være bedre om vi heller parser JSON output fra den andre scannejobben og skriver ut en tabell selv. Dette er helt topp for en første versjon!

2023-06-13 15:10 UTC, stigok commented on .github/workflows/workflow.yaml
> +        description: Render a table of all the Trivy findings in the Github summary for the workflow
GitHub med stor H og punktum til slutt.

2023-06-14 08:14 UTC, siljekristensen commented
> Tror på sikt det vil være bedre om vi heller parser JSON output fra den andre scannejobben og skriver ut en tabell selv. Dette er helt topp for en første versjon!

Tenkte at denne kommentaren er relevant for denne diskusjonen: https://github.com/aquasecurity/trivy/issues/3243#issuecomment-1470823835

2023-06-14 18:56 UTC, stigok approved these changes

2023-06-15 06:15 UTC, merged